### ISSUE TITLE
[BUG] Nest multiple schemas using $ref

### ISSUE THREAD

**Issue by valkirilov** [JaredCE/serverless-openapi-documenter#103]
**Describe the bug**
In an attempt to maximize the reuse of my JSON schemas, I have opted to utilize the `$ref` feature to establish connections and relationships within my payloads. However, I have encountered some challenges when attempting to construct a chain of multiple schemas that reference themselves (like `Grandpa` -> `Parent` -> `Child`).

**To Reproduce**
Starting with a simple example, if I have the following schemas:

_PS: I decided to keep my schemas as simple as possible, for the sake of the example._

- `src/serverless/schemas/Child.json`
```
{
  "title": "Child",
  "type": "object",
  "properties": {
    "child_property": {
      "type": "string"
    }
  }
}
```

- `src/serverless/schemas/Parent.json`
```
{
  "title": "Parent",
  "type": "object",
  "properties": {
    "parent_property": {
      "type": "string"
    },
    "child_reference": {
      "$ref": "src/serverless/schemas/Child.json"
    }
  }
}
```
&nbsp;

**_Note:_** _By providing a `$ref` that points to the full path of the child schema (`src/serverless/schemas/Child.json`), I was able to successfully implement the solution. However, I encountered an issue where, according to the specification, I should be able to utilize a relative path instead, as demonstrated below:_
```
"child_reference": {
      "$ref": "Child.json"
}
```
Reference:
- [Relative References in URLs | OpenAPI Specification
](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#relative-references-in-urls)
> Relative references used in $ref are processed as per JSON Reference, using the URL of the current document as the base URI. See also the Reference Object.

&nbsp;
&nbsp;

I bring this up because I believe it may be connected to the issues I am about to describe. If we choose to proceed with utilizing full paths, we will likely encounter another problem as we introduce an additional level in the inheritance tree, such as adding the **Grandpa** schema above the **Parent** schema:
```
{
  "title": "Grandpa",
  "type": "object",
  "properties": {
    "grandpa_property": {
      "type": "string"
    },
    "parent_reference": {
      "$ref": "src/features/songs/serverless/schemas/Parent.json"
    }
  }
}
```

I end up with the following error message caused by some bad built-up of the pathname:
```
Error:
ServerlessError: ResolverError: Error opening file "/home/user/project/src/serverless/schemas/src/serverless/schemas/Child.json"
ENOENT: no such file or directory, open '/home/user/project/src/serverless/schemas/src/serverless/schemas/Child.json'
```

You can see how it messed up the path by duplicating the `src/serverless/schemas/`, the part that I added in the first place because it doesn't resolve properly the relative path. So I believe that I don't construct it the correct way.

And here, you can see some really odd behavior if you start playing with the pathnames:
- providing relative path results in an attempt to reference the file from the root
```
"parent_reference": {
      "$ref": "./Parent.json"
 }

ServerlessError: ResolverError: Error opening file "/home/user/project/Parent.json"
ENOENT: no such file or directory, open '/home/user/project/Parent.json'
```
- but if we provide a full path, but with a typo (intentionally changed `schemas` to `schema` so it points to not valid path) it does resolve it correctly (compare it back to the initial example where we provide the correct path, but it duplicated it for some reason):
```
"parent_reference": {
      "$ref": "src/serverless/schema/Parent.json"
 }


ServerlessError: ResolverError: Error opening file "/home/user/project/src/serverless/schema/Parent.json"
ENOENT: no such file or directory, open '/home/user/project/src/serverless/schema/Parent.json'
```

I'm aware of a similar issue that is currently active, but I decided to create a separate issue, so we don't mix up both things:
- https://github.com/JaredCE/serverless-openapi-documenter/issues/97

**Expected behavior**
My expectations were that I can build up a tree deeper than one level (using references to other schemas).

**Desktop (please complete the following information):**
 - Serverless version: 3.0.0
 - serverless-openapi-documenter version 0.0.49

**Comment by valkirilov** [comment]
To address the issue at hand, I implemented a temporary workaround by utilizing a custom reference resolver. According to the documentation, it's possible to customize the behavior of the `@apidevtools/json-schema-ref-parser` dependency by overriding its default configuration for resolving file paths. Following your instructions, I created a custom `ref-parser` and attempted to configure it in a manner that would work for our specific use case, even though it may seem like a somewhat hacky approach.

- `options/ref-parser.js`
```js
'use strict'
const path = require('path')
const fse = require('fs-extra')

// options from: https://apitools.dev/json-schema-ref-parser/docs/options.html
module.exports = {
    parse: {
        json: true,
    },
    resolve: {
        file: {
            order: 1,
            canRead(file) {
                try {
                    path.resolve(file.url)
                    return true
                } catch (e) {
                    return false
                }
            },
            read(file) {
                const fileName = path.relative(process.cwd(), path.resolve(file.url))
                const currentDir = file.url.replace(fileName, 'src/')
                const filePath = findFileRecursively(fileName, currentDir)

                return fse.readFile(filePath, 'utf8')
            },
        },
    },
    dereference: {
        circular: true,
    },
}

function findFileRecursively(filename, directory) {
    const files = fse.readdirSync(directory)

    for (const file of files) {
        const filePath = path.join(directory, file)
        const stats = fse.statSync(filePath)

        if (stats.isDirectory()) {
            const result = findFileRecursively(filename, filePath)
            if (result) {
                return result
            }
        } else if (file === filename) {
            return filePath
        }
    }

    return null
}
```


By implementing a simple script to configure our own resolver, we are now able to perform a custom search within the project source code when the documentation generation encounters a `$ref`. As a result, we can easily find and resolve the proper JSON schema. With this approach, we can simply use a relative path to reference the desired schemas in our JSON files, eliminating any issues related to path build-up which was initially reported here.

- `src/serverless/schemas/Child.json`
```json
{
  "title": "Child",
  "type": "object",
  "properties": {
    "child_property": {
      "type": "string"
    }
  }
}
```

- `src/serverless/schemas/Parent.json`
```json
{
  "title": "Parent",
  "type": "object",
  "properties": {
    "parent_property": {
      "type": "string"
    },
    "child_reference": {
      "$ref": "Child.json"
    }
  }
}
```

- `src/serverless/schemas/Grandpa.json`
```json
{
  "title": "Grandpa",
  "type": "object",
  "properties": {
    "grandpa_property": {
      "type": "string"
    },
    "parent_reference": {
      "$ref": "Parent.json"
    }
  }
}
```

Here's what the output of the above configuration looks like after running the command to generate the documentation:
```json
"Grandpa": {
  "title": "Grandpa",
  "type": "object",
  "properties": {
    "grandpa_property": {
      "type": "string"
    },
    "parent_reference": {
      "title": "Parent",
      "type": "object",
      "properties": {
        "parent_property": {
          "type": "string"
        },
        "child_reference": {
          "title": "Child",
          "type": "object",
          "properties": {
            "child_property": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

Even though we were able to come up with a temporary solution for our current situation, I'll keep the issue open just in case the library author decides to implement a proper fix. I think that the problem we faced is actually a fairly common scenario, given that reusability of JSON schemas is such a handy and widely used feature.

**Comment by JaredCE** [comment]
Hey @valkirilov, apologies for not getting back to you in a timely manner.  

I've just pushed out 0.0.60 which contains a huge rewrite of the schema handling.  I have also tried to recreate your example issue in a new serverles example file: https://github.com/JaredCE/serverless-openapi-documenter/blob/main/test/serverless-tests/schemas/serverless.yml

You'll note from there I have created a model `GetResponse`:

```
- name: GetResponse
        description: The Get Response
        contentType: application/json
        schema: ${file(resources/schemas/Parent.json)}
```
It uses serverless yaml parser to pull in the JSON file `Parent.json` which will resolve to: https://github.com/JaredCE/serverless-openapi-documenter/blob/main/test/serverless-tests/schemas/resources/schemas/Parent.json

Within that file, you'll see i'm creating a reference to Child.json:

```
"child_reference": {
        "$ref": "./resources/schemas/Child.json"
}
```

When you run the generator: `npx serverless openapi generate -o openapi.json -f json -a 3.0.3` it'll start generating from the working directory `serverless-openapi-documenter/test/serverless-tests/schemas` and we're storing our schema files in `serverless-openapi-documenter/test/serverless-tests/schemas/resources/schemas/`.  So using a $ref like: `"$ref": "./resources/schemas/Child.json"` means `@apidevtools/json-schema-ref-parser` look through the folder resources/schemas for the referenced file, this is without any extra configuration.

This generates a schema in the components like:

```
"GetResponse": {
        "title": "Parent",
        "type": "object",
        "properties": {
          "parent_property": {
            "type": "string"
          },
          "child_reference": {
            "title": "Child",
            "type": "object",
            "properties": {
              "child_property": {
                "type": "string"
              }
            }
          }
        }
      },
```

I hope this helps, please let me know if it doesn't or if you come accross any issues.  Referencing in JSON is still a bit of a pain and i haven't solved for everything, but the more bugs i hear about the better I can try and fix them.

**Comment by valkirilov** [comment]
Thank you @JaredCE for your time and effort! I have pulled your latest version and tried to see how it goes with my example. It was okay with schemas nested only on one level, as you provided with your example (Parent -> Child). Still, unfortunately, it seems to fail again when we have deeper relationships like `Granpa` -> `Parent` -> `Child` and so on. 

This time I've prepared an example repository where you can see my setup and let me know if I built it wrong:
- [Example Repository](https://github.com/valkirilov/serverless-openapi-documenter-example)

You can find the JSON schemas and how they're defined:
- [Child.json](https://github.com/valkirilov/serverless-openapi-documenter-example/blob/main/src/features/echoHelloWorld/serverless/schemas/Child.json)
- [Parent.json](https://github.com/valkirilov/serverless-openapi-documenter-example/blob/main/src/features/echoHelloWorld/serverless/schemas/Parent.json)
- [Grandpa.json](https://github.com/valkirilov/serverless-openapi-documenter-example/blob/main/src/features/echoHelloWorld/serverless/schemas/Grandpa.json)
- [GrandChild.json](https://github.com/valkirilov/serverless-openapi-documenter-example/blob/main/src/features/echoHelloWorld/serverless/schemas/GrandChild.json)

Here is how the generated schemas look like:
```json
"GrandChild": {
  "title": "GrandChild",
  "type": "object",
  "properties": {
    "grandChild_property": {
      "type": "string"
    }
  }
},
"Child": {
  "title": "Child",
  "type": "object",
  "properties": {
    "child_property": {
      "type": "string"
    },
    "grandChild_reference": {
      "title": "GrandChild",
      "type": "object",
      "properties": {
        "grandChild_property": {
          "type": "string"
        }
      }
    }
  }
},
"Parent": {
  "title": "Parent",
  "type": "object",
  "properties": {
    "parent_property": {
      "type": "string"
    },
    "child_reference": {
      "$ref": "./src/features/echoHelloWorld/serverless/schemas/Child.json"
    }
  }
},
"Grandpa": {
  "title": "Grandpa",
  "type": "object",
  "properties": {
    "grandpa_property": {
      "type": "string"
    },
    "parent_reference": {
      "$ref": "./src/features/echoHelloWorld/serverless/schemas/Parent.json"
    }
  }
},
```

You can see that the first two schemas (`GrandChild` and `Child`) are okay, but then the paths aren't resolved properly once we try to reference them from the `Parent` or `GrandParent` schemas.

You can give it a try on your own as well:
```
npm run generate:open-api-docs
```

**Comment by JaredCE** [comment]
Ok this is very odd

I was messing about with the path in your example repo and outputting the error.

So you're right, `Child` and `GrandChild` are fine, but once you get to `Parent` it seems to break.  So messing about a little, I changed `Child.json` to be:

```
{
  "title": "Child",
  "type": "object",
  "properties": {
    "child_property": {
      "type": "string"
    },
    "grandChild_reference": {
      "$ref": "./GrandChild.json"
    }
  }
}
```

Now by doing this, it breaks the de-referenced Child.json in the final openAPI doc, but fixes Parent.json to include Child and GrandChild properties 🧐🤷🏻.

I don't think this is a bug I can fix, I think it's a bug with the now kinda out of maintenance https://github.com/APIDevTools/json-schema-ref-parser library.  I suspect the best solution to this is the one you've already come up with using the `ref-parser.js` options file to augment the reading of files. 

i've only had a play with your example for about 30 minutes, i'll find some time to have a longer play and debug, but at the moment it's very much looking like the ref-parser library is messing up.

**Comment by valkirilov** [comment]
I appreciate the time you've spent on my report. I also think that the problem is connected to the path resolution, which is managed by the external dependency. Therefore, I will continue using the current workaround I discovered using a custom "ref-parser," but I will keep looking at the discussion for any future upadtes. Thank you!

**Comment by JaredCE** [comment]
The other thing you can do, now that 0.0.60 is out is change your references so that they read as:

```
"grandChild_reference": {
     "$ref": "#/components/schemas/GrandChild"
}
```

Swagger, or whatever tool you're then using to display the openAPI spec, should be able to piece together how it should look. You can try here: https://editor.swagger.io/ (if you make those changes to your example repo, then generate the openAPI file and paste it into there, it outputs pretty nicely)

This does require all your  referenced schema files to be listed in `models`, whether you're using them directly (like in a `requestBody`) or not, so if you had a schema `Cousin.json` but weren't using it directly anywhere, you'd need to list it under `models`, but update any model requireing it to read:

```
"cousin_reference": {
     "$ref": "#/components/schemas/Cousin"
}
```

if that makes sense.

**Comment by JaredCE** [comment]
I think this is as resolved as it can be for now.  Please re-open or open a new issue if you're having any more difficulty or have questions about schemas/models and openAPI generation.

Thanks
