### ISSUE TITLE
[Request] integrate with serverless Request Schema Validators

### ISSUE THREAD

**Issue by dhmw** [JaredCE/serverless-openapi-documenter#109]
Hi there,

I'm really interested in using this plugin to generate API specs, but I am struggling with having to define my request models twice, as I already use [Request Schema Validators](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#request-schema-validators).

Is there a good reason why this plugin wants to define its own separate request models, when Request Schema Validators uses the same JSON schema, and also ensures at the API Gateway level that the request will be validated?

Regards,
Doug

**Comment by JaredCE** [comment]
Hey @dhmw, I have just pushed out 0.0.64 which now allows use of Request Schema Validators which means you don't have to define them either under `models` or in `requestModels`.  You can use them in all the ways [serverless Request Schema Validators](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#request-schema-validators) allows for, and the generator should match them up and add schemas to the schema references.

There are still some improvements to be made, so it's not 100% amazing, but i think it should get you started with using this plugin.

If you find some issues with it, please do let me know and i'll try and get them fixed.  TBH the code base needs a bit of a rewrite now, but that's my own fault.

**Comment by JaredCE** [comment]
Hey @dhmw haven't heard back good or bad, so going to assume it's all good now.  Going to close this issue, but feel free to raise an issue if you have problems with this implementation or anything else.
