### ISSUE TITLE
[BUG] Missing 4xx response throws error, breaking existing implementation

### ISSUE THREAD

**Issue by karmaniverous** [JaredCE/serverless-openapi-documenter#153]
**Describe the bug**
Somewhere between `0.0.72` and `0.0.90` this plugin began throwing errors when no 4xx response is configured. 

Not saying this is wrong, but it DOES throw errors on all of our existing services, none of which have 4xx responses configured, and all of which previously compiled without error.

I would characterize this as a breaking change, deserving of a major version release. As an alternative, I would suggest that this case throw warnings rather than errors.

Here's what we are seeing:

```bash
OpenAPI v3 Description Generation
[OPTIONS]
  openApiVersion: "3.0.0"
  format: "json"
  output file: "api/openapi.json"
  indentation: "2"
  validationWarn: false
  postman collection: api/postman.json
Generating OpenAPI Description
Validating generated OpenAPI Description
× ERROR: An error was thrown validating the OpenAPI v3 Description
× [VALIDATION] Validation errors found in OpenAPI Description:

× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1doc~1openapi/get/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1doc~1postman/get/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1my~1account/get/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1my~1account/put/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1my~1accounts/get/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1private~1account/get/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1private~1account/put/responses
× Message: Operation must have at least one `4XX` response.
× found at location: #/paths/~1private~1accounts/get/responses
Environment: win32, node 18.12.1, framework 3.32.2 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
ServerlessError: Error validating OpenAPI Description:
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
Operation must have at least one `4XX` response.
```

**To Reproduce**

Write any endpoint without a 4xx response.

**Expected behavior**
The plugin should throw warnings instead of errors.

**Desktop (please complete the following information):**
 - Serverless version:
   - Framework Core: 3.32.2 (local) 3.34.0 (global)
   - Plugin: 6.2.3
   - SDK: 4.3.2
 - serverless-openapi-documenter version: 0.0.90

**Comment by JaredCE** [comment]
0.0.90 would have contained that change.  I switched from my previous OpenAPI validator to the Redocly validator and added these rules

[spec](https://redocly.com/docs/cli/rules/spec/)
[path-parameters-defined](https://redocly.com/docs/cli/rules/path-parameters-defined/)
[operation-2xx-response](https://redocly.com/docs/cli/rules/operation-2xx-response/)
[operation-4xx-response](https://redocly.com/docs/cli/rules/operation-4xx-response/)
[operation-operationId-unique](https://redocly.com/docs/cli/rules/operation-operationid-unique/)
[path-declaration-must-exist](https://redocly.com/docs/cli/rules/path-declaration-must-exist/)

as of... an 0.0.8x release, i did add the cli option of `-w true` to switch validation errors to ignorable warnings.  Adding in `-w true` will output validation errors, but still generate the OpenAPI Description for you.

**Comment by karmaniverous** [comment]
Ah excellent that works thank you!
