### ISSUE TITLE
[HELP NEEDED] Generating OpenApi definition based on serverless.ts

### ISSUE THREAD

**Issue by shayan919293** [JaredCE/serverless-openapi-documenter#191]
Hi everyone, 

I'm having issues generating my [paths] on openapi.json or openapi.yml file. 
I defined "documentation" under "custom" in serverless.ts file and I can see my schema correctly in openapi file.
but can't seem to make the functions + paths to show up on openapi definition file. 
My functions are well defined and actually work as well. 

Does this plugin work with serverless.ts files same as serverless.yml files?  

Please let me know if I could provide more information on this.

**Comment by JaredCE** [comment]
I'm going to close this as i haven't heard back, feel free to re-open if you have additional info to add.
