### ISSUE TITLE
[BUG] Cannot read property 'documentation' of undefined

### ISSUE THREAD

**Issue by cbm-eheude** [JaredCE/serverless-openapi-documenter#21]
**Describe the bug**
When event is httpApi Cannot read property 'documentation' of undefined exception is raised

**To Reproduce**
Create a lambda with httpApi event
```
functions:
myLambda:
...
events:
- httpApi:
  method: GET
  path: hello
  documentation:
    ....
  ...
```
**Expected behavior**
No exception raised and open API file generated 

**Desktop (please complete the following information):**
 Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.19.1
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2

**Additional context**

A possible solution, on method `createPaths` of definitionGenerator.js file there are missing questions mark
```
const documentation = event.http.documentation || event.httpApi.documentation
````
should be
```
const documentation = event.http?.documentation || event.httpApi?.documentation
```

**Comment by cbm-eheude** [comment]
In fact i think httpApi is not fully managed

**Comment by JaredCE** [comment]
@cbm-eheude you're right.  I think I have a fix for this along with some other issues on my other machine.  Will try and get it out tonight or tomorrow

**Comment by JaredCE** [comment]
@cbm-eheude I have released a new version.  If you'd like to try that and feel free to let me know any issues you may find with it.

**Comment by cbm-eheude** [comment]
@JaredCE it's working now thanks !

**Comment by JaredCE** [comment]
That's great.  I'm sure there are some other gotchas in there that I need
to work through.

Sorry it didn't work first time round.
