### ISSUE TITLE
[BUG] x-tagGroups, x-displayName

### ISSUE THREAD

**Issue by shudac** [JaredCE/serverless-openapi-documenter#221]
**Describe the bug**
x-tagGroups property appears in info section od openapi.json, not in the root.
x-displayName property of the tag object within the tags array is not transfered to openapi.json

**To Reproduce**
```
version: "1.0.0"
title: "Test API"

tags:
  - name: product
    x-displayName: Product,
    description: Product endpoints
  - name: user
    x-displayName: User,
    description: User endpoints

x-tagGroups:
  - name: Admin
    tags:
      - product
      - user

models: ${file(generated/models.yml):models}
```
**Expected behavior**
x-tagGroups property defined in the root of the documentation should appear in the root of the generated openapi.json file at the same level as tags or models properties.

x-displayName property of the tag object within the tags array should remain at the same position.

**Desktop (please complete the following information):**
 - Serverless version: [e.g. 3.38.0]
 - serverless-openapi-documenter version [e.g. 0.0.103]

**Additional context**
https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups
https://redocly.com/docs/api-reference-docs/specification-extensions/x-display-name

**Comment by JaredCE** [comment]
Hey @shudac I have just pushed a new version that should do what you want.  If you update to 0.0.104 you'll have better `x- support and `x-tagGroups` added to the right place.  Let me know if you have any issues.

**Comment by JaredCE** [comment]
Hey @shudac I'm going to close this off now, please open a new issue if you find anything else.  Thanks!
