### ISSUE TITLE
[Help Needed] Add typescript support

### ISSUE THREAD

**Issue by JaredCE** [JaredCE/serverless-openapi-documenter#68]
I'm still fairly new to TypeScript.  I might spend my holidays looking at how to implement it properly, but would be great to get some help on making this project TypeScript compatible.

**Comment by nathanagez** [comment]
@JaredCE, how can I help you ?

**Comment by JaredCE** [comment]
@nathanagez So I'd like to make sure this project can be used in TypeScript projects without triggering warnings and lint errors.  Admittedly I haven't got any typescript projects running at the moment so I don't know what it might be doing.  

I see you have a TypeScript serverless plugin here: https://github.com/nathanagez/serverless-typeorm-migrations 

I was looking for something like this, fairly simple, that I can roughly copy and get running... though I note you've written `.ts` files, and I was hoping to keep it very simple to start with and just provide the minimum without converting things to `.ts`.  So any advice along those lines.  Any "So you want to convert a library to TS" type articles I can read through.

**Comment by gymstory** [comment]
@JaredCE  Could you maybe elaborate on what you mean with this ticket, as I currently have a working setup in typescript, with this plugin, and thought that it could potentially be useful for others.

**Comment by JaredCE** [comment]
Hey @gymstory I think really this can be closed off.  I don't think the plugin needs a rewrite in typescript.  I think this was a misunderstanding on my part, i thought if i wrote it in ts, it would expose the schema for how the documentation should be written and help people with auto-complete.  But this isn't how plugins work for serverless so wouldn't make a difference.

**Comment by gymstory** [comment]
@JaredCE I see. It Indeed doesn't make a difference to implementers if the plugin in TS.

**Comment by JaredCE** [comment]
That's excellent.  i'll close this off.  

Let me know if there are other areas this plugin can be improved.
